services:
  api:
    build:
      context: ../..
      dockerfile: code/deployment/api/Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ../../models:/models
    networks:
      - net

  app:
    build:
      context: ../..
      dockerfile: code/deployment/app/Dockerfile
    ports:
      - "8090:8090"
    environment:
      - BACKEND_URL=http://api:8000
    networks:
      - net

networks:
  net:
    driver: bridge